spring:
  cloud:
    consul:
      discovery:
        health-check-interval: 3s
        health-check-path: /actuator/health
        heartbeat:
          enabled: true
        health-check-url: ${spring.cloud.client.ip-address}:${server.port}
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
        logger-level: basic