spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: duwa-cloud-consumer
          uri: lb://duwa-cloud-consumer
          predicates:
            - Path= /consumer/**
          filters:
            - StripPrefix=1
        - id: duwa-cloud-provider
          uri: lb://duwa-cloud-provider
          predicates:
            - Path= /provider/**
          filters:
            - StripPrefix=1
    consul:
      discovery:
        health-check-interval: 3s
        health-check-path: /actuator/health
        heartbeat:
          enabled: true
        health-check-url: ${spring.cloud.client.ip-address}:${server.port}
  redis:
    host: 10.0.0.203
    port: 6379